baseURL = "https://dannyholmes.com/"
languageCode = "en-gb"
title = "Danny Holmes"
copyright = "Copyright Danny Holmmes. All rights reserved."
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "northumbria-advanced-motorcyclists"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "G-1TBBFM6E0Z"
theme = "namrider"
assetDir = "themes/namrider/assets"
relativeURLs = true
buildFuture = true
# Add code highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
# Miscellaneous
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = false
# RSS
rssLimit = 100

# Define how many pages appear per site
[pagination]
  disableAliases = false
  pagerSize = 12
  path = 'page'

[params]
    debug = false
    site_author = "Danny Holmes"
    site_logo = ""
    short_title = "dannyholmes.com"
    site_description = "Helping to promote motorcycle road safety across Northumberland, Newcastle and the North East. Find out pass your advanced motorcycle road test."
    location = "Northumberland, England"
    description = "Welcome to my digital playground and scrapbook."
    # Link custom assets relative to /static
    avatar = "img/NAM_Logo.png"
    favicon = ""
    header_background = "img/northumbria_advanced_motorcyclists_event1_1140x760.jpg"
    header_title = "Danny Holmes"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []
    minify = true
    datatables = false
    rss = ""
    rssPageType = ["news", "posts", "events"]
    [params.author]
      name = "Danny Holmes"
      email = "hi@dannyholmes.com"
    [params.sass]
      includePaths = ["node_modules"]

    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    featured_image = "/images/gohugo-default-sample-hero-image.jpg"
    recent_posts_number = 2

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = ""
    weight = 100

  [[menu.main]]
    identifier = "motorcycling"
    name = "Motorcycling"
    url = "/motorcycling/"
    weight = 110

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/diesel-therapy"
    weight = 120

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 150

  [[menu.main]]
    identifier = "routes"
    name = "Routes"
    url = "/motorcycle-routes/"
    weight = 160

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 170

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  event_type = "event_types"
  route_direction = "route_directions"
  route_town = "route_towns"
  route_road = "route_roads"
  route_cafe = "route_cafes"

[outputs]
    page = ["HTML"]
    home = ["HTML","RSS"]
    section = ["HTML","RSS"]
    term = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "rss"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    youtube = ""
    github    = ""
    gitlab = ""
    mastodon = ""
    slack = ""
    stackoverflow = ""
    gplus     = ""

[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "lanczos"
  # Default JPEG quality setting. Default is 75.
  quality = 85
  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"

[params.imaging]
  # xl, lg, md, sm and below
  sizes = ["1200","700","340"]

[params.contact]
  phone = "0191 364 3264"

[params.accounts]
    # Bank account details
    names = ["events","training","social"]
    sortCodes = ["XX-XX-XX", "XX-XX-XX", "XX-XX-XX"]
    accountNumbers = ["XXXXXXXX","XXXXXXXX","XXXXXXXX"]
    accountNames = ["","",""]

[params.private]
    # Exclude from sitemaps
    privateDirs = ["overview","timeline","events","faq","news","motorcycle-routes","documents", "leaflet"]

[params.robots]
    # Set no-follow in robots meta tag
    nofollowTypes = ["events","news","posts"]

[frontmatter]
date = ["eventStartDate", "lastRideDate", ":default"]

# Check usage!

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[build]
  [build.buildStats]
    enable = true

[module]
  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"
  
  [[module.mounts]]
    source = "themes/namrider/assets"
    target = "assets"
  
  [[module.mounts]]
    source = "themes/namrider/static"
    target = "static"
  
  [[module.mounts]]
    source = "themes/namrider/layouts"
    target = "layouts"
  
  [[module.mounts]]
    source = "themes/namrider/data"
    target = "data"
  
  [[module.mounts]]
    source = "themes/namrider/i18n"
    target = "i18n"
  
  [[module.mounts]]
    source = "themes/namrider/archetypes"
    target = "archetypes"
  
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  
  [[module.mounts]]
    source = "static"
    target = "static"